# Site settings
title: Ben Chan Tech LLC
description: >-
   Engineering systems at the edge of tech, music, and language.
url: "https://benchantech.com"
baseurl: ""

# Build settings
theme: minima
markdown: kramdown
highlighter: rouge
timezone: America/New_York

# Permalinks
permalink: /:categories/:title/

# Header navigation
header_pages:
  - index.md

# Custom includes
include:
  - _includes/head-custom.html
  - assets/images

# Minima theme customization
minima:
  skin: classic
  social_links:
    github: Ben Chan Tech
    linkedin: Ben Chan Techllc
    youtube: benchanviolin
    email: ben@benchantech.com

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
