"use client";

import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { cx } from "@/components/provenance/cx";
import { RESULT } from "@/content/trust-forward/copy";
import {
  closingUpsell,
  deterministicSummaryFraming,
  finalRevealBlock,
  learnerWordsBlock,
  learnerWordsCaseLabel
} from "@/content/trust-forward/surfaces";
import type {
  ClipboardSummaryField,
  ClipboardSummaryFieldId
} from "@/lib/trust-forward/exports";
import { observedPatternLabel, profileFor } from "@/lib/trust-forward/profiles";
import { compareReceiptsForHighlight } from "@/lib/trust-forward/receipts";
import type { CaseNumber, LiteResult, ShipAxis } from "@/lib/trust-forward/types";
import { ShipBars, type ShipAxisEnds } from "./ShipBars";
import styles from "./reveal.module.css";

/**
 * Trust Forward Lite — the final reveal (plan step 10; INSTALLATION.md
 * "Phase 10 — Final result"; UX_COPY.md "## Final result"; the layer-06
 * recovered five-case source, "Your five cases are complete").
 *
 * FOUR BLOCKS, IN THE RECOVERED SOURCE'S ORDER, AND THE ORDER IS THE ARGUMENT:
 *
 *   1. The completion statement. Lite followed rules written in advance, and
 *      nothing in the profile was generated by AI.
 *   2. The result. The observed-pattern label, the code, the sixteen-profile
 *      name and special ability, the four neutral two-ended leans, the compact
 *      synthesis, the recovered 729-state terminal narrative, and the sentence
 *      that says the narrative describes selections rather than a person.
 *   3. "What you actually wrote" — the learner's reflections, replayed
 *      verbatim, with nothing done to them.
 *   4. The closing upsell: what Lite could do, the eight things it could not,
 *      and where the other thing lives.
 *
 * BLOCK 3 IS THE PRODUCT'S ARGUMENT, NOT A COURTESY. The recovered source's own
 * note on it is "No synthesis", and the line after that is the point: the block
 * "visually demonstrates the giant unused signal sitting right in front of
 * them." Five pieces of a developer's own reasoning, sitting on the page,
 * untouched — because a deterministic system cannot touch them. Block 4's
 * eight-item "It could not:" list is that demonstration turned into sentences,
 * and its first item is "interpret what you wrote". So block 3 is never
 * summarised, never truncated, never reordered and never collapsed behind a
 * disclosure: doing any of those would turn the demonstration into a claim, and
 * the claim in block 4 would then have nothing standing behind it.
 *
 * That is also why `REFLECTION.disclosure`'s promise — "preserved exactly as
 * you wrote them" — is a rendering requirement here and not only a storage one.
 * `.wordsText` sets `white-space: pre-wrap`; the text reaches the DOM through no
 * trim, no normalisation and no ellipsis.
 *
 * NOT ONE SENTENCE IS TYPED IN THIS FILE. Every string comes from
 * `content/trust-forward/copy.ts` or `content/trust-forward/surfaces.ts`, or
 * arrives as a prop. `tests/canonical-text.test.ts` fails on any prose of
 * twelve words or more that a file under `app/` or `components/` types for
 * itself, and that test is the mechanism behind "all learner-facing prose is
 * governed content" — without it, the content registry governs a directory a
 * component could simply bypass.
 *
 * ## Three rules this component exists to keep
 *
 * **The code is never a second-person predicate.** `observedPatternLabel` in
 * `lib/trust-forward/profiles.ts` is the only sanctioned constructor for
 * putting a code in front of a learner, and it validates its own output. It is
 * used here for the result group's accessible name, so the permitted form is
 * what a screen reader announces; on screen the label and the code are two
 * elements, which is the same statement with better typography. The word
 * "observed" in `RESULT.label` is doing the work in both.
 *
 * **The bars cannot rank.** `ShipBars.tsx` owns that constraint and carries the
 * reasoning; this file mounts it and must not add a colour, an ordering or an
 * adjective around it.
 *
 * **The receipts shown are the ACTIVE trail, never inactive history.**
 * `INSTALLATION.md`: "`See full` reveals all current active fixed-answer
 * receipts; never show inactive history." `LiteResult.receipts` is by contract
 * that trail — `allReceipts` builds it from the active path, and superseded
 * answers stay in the ledger and the JSON export where a learner can still see
 * them. This component sorts a COPY for the highlight view and never re-derives
 * or mutates the trail, so "See full" cannot show a receipt the export would
 * not.
 *
 * ## What is deliberately absent
 *
 * The professional-summary block. The recovered source has one ("A professional
 * version you can keep"), and `content/trust-forward/copy.ts` exports
 * `TODO_RESULT_PROFESSIONAL_SUMMARY` as `null` instead of wording, because the
 * recovered `market_copy` column and layer 07 give contradictory instructions:
 * layer 07 keeps a professional summary but marks it implementation-authored
 * from market vocabulary rather than recovered, while dropping the old
 * three-value `profile_headline` that column still carries. Nothing renders in
 * its place and no placeholder is drawn — an invented paragraph there would be
 * indistinguishable from recovered wording once it is on the page, which is the
 * failure `TRUST_FORWARD_PROVENANCE.md` forbids by name. The insertion point is
 * marked in the JSX.
 *
 * ## Why this component owns no data
 *
 * It reads no storage, writes no ledger event, fires no telemetry and touches
 * no URL. Everything arrives as props and every action leaves as a callback,
 * for two reasons that are not style:
 *
 *  - `README.md`'s locked UX and `tests/no-private-state-in-urls.test.ts` put
 *    the whole five-case run at ONE URL with state in local storage, because
 *    GA4 ships `send_page_view: true` and a URL is therefore telemetry. A
 *    component that navigated in order to encode a result would publish it.
 *  - The ledger is append-only, and its `result_viewed`, `result_detail_viewed`,
 *    `export_markdown`, `export_json`, `copy_summary` and `reset` events belong
 *    to whoever owns the dataset. Two writers to one sequence is how a ledger
 *    stops being a record.
 *
 * The telemetry callbacks are OPTIONAL because the island that mounts this
 * already fires `result_viewed` from its own effect. A caller that has not
 * wired an event yet gets a working reveal rather than a crash, and the ledger
 * is never half-written by two authors.
 */

/**
 * One case's reflection, as the learner typed it.
 *
 * Structurally a subset of `ExportReflection`, so the island can pass
 * `activePathReflections(...)` straight through: the reveal and the export show
 * the same words from the same selector, which is what makes "your export
 * contains what you just read" true rather than nearly true.
 */
export interface RevealReflection {
  caseNumber: CaseNumber;
  /** Verbatim. Not trimmed, not normalised, not shortened. */
  text: string;
}

/**
 * The action labels the approved sources do not supply.
 *
 * `UX_COPY.md`'s "## Final result" words five controls exactly — the receipts
 * toggle, `See full`, the completion CTA, `Reopen your decisions` and
 * `Start over` — and those come from `RESULT`, never from here. It names the
 * export and copy controls WITHOUT wording them ("export + copy actions"), and
 * `INSTALLATION.md` specifies the two-step destructive confirmation and the
 * completed learner's "Export first" as BEHAVIOUR with no strings at all.
 *
 * So they are props. Typing seven plausible button labels into this file would
 * put seven unsourced learner-facing strings on the page wearing the same
 * provenance as the recovered sentences around them, with nothing in the
 * repository recording the difference — the one thing
 * `TRUST_FORWARD_PROVENANCE.md` forbids outright. A composition root has to get
 * them from somewhere, and the right somewhere is a governed content record
 * carrying an `implementation_authored_under_ben_approved_rule` tag.
 *
 * AND THEY ARE OPTIONAL, WHICH IS THE SAME DECISION AS `AwaitingCopy`
 * ELSEWHERE IN THIS REPO. Without them the export/copy row and the destructive
 * control DO NOT RENDER — not disabled, not stubbed, not labelled with a
 * plausible verb. A missing button is a gap somebody can see; an invented label
 * is a gap nobody can. `RESULT.destructiveCta` is authored and exists, but its
 * second step is not, and a one-step `Start over` is a different control from
 * the one `INSTALLATION.md` specifies, so the whole two-step control waits for
 * its confirmation words rather than shipping half of itself.
 */
export interface RevealActionLabels {
  exportMarkdown: string;
  exportJson: string;
  /** Opens the field list. EXPORT_SPEC.md: checkbox selection BEFORE any copy. */
  copySummary: string;
  /** Performs the copy over the checked fields. */
  copyConfirm: string;
  /** INSTALLATION.md: "Completed user gets Export first." */
  startOverExportFirst: string;
  startOverConfirm: string;
  startOverCancel: string;
}

export interface RevealProps {
  /**
   * The complete result. Its existence IS the completeness gate: an unanswered
   * active decision means no result and no export at all (plan §6.4), so a
   * caller holding one has already passed the gate. This component therefore
   * never renders a partial, greyed-out or "almost there" reveal, and the
   * learner who edits an upstream answer sees the reveal disappear rather than
   * dim.
   */
  result: LiteResult;
  /** In experience order, as stored. Never reordered here — see `writtenReflections`. */
  reflections: readonly RevealReflection[];
  /** The learner's local handle, if they set one. Never scored, never transmitted. */
  handle?: string | null;
  /**
   * From `clipboardSummaryFields`. Each row is a preview of the value that
   * would be pasted, not merely its name. `null` when no summary can be built,
   * in which case the copy control does not render at all.
   */
  clipboardFields?: readonly ClipboardSummaryField[] | null;
  /** Absent until the seven strings are authored. See `TODO_REVEAL_ACTION_LABELS`. */
  labels?: RevealActionLabels | null;
  onExportMarkdown: () => void;
  onExportJson: () => void;
  onCopySummary: (selected: readonly ClipboardSummaryFieldId[]) => void;
  onReopenDecisions: () => void;
  onStartOver: () => void;
  /** Fired by both controls that point at full Trust Forward. */
  onContinueToFull?: () => void;
  /**
   * The "Export first" offer inside the destructive confirmation. Defaults to
   * the JSON export, which is the only artifact carrying the whole ledger — the
   * part of a learner's run that clearing local storage actually destroys.
   */
  onExportFirst?: () => void;
  /** `result_viewed`. Fired once per mount, only if the island does not own it. */
  onViewed?: () => void;
  /** `result_detail_viewed`, on opening "Why this result?". */
  onReceiptsOpened?: () => void;
  /** `result_detail_viewed`, on "See full". */
  onSeeAllReceipts?: () => void;
  /**
   * How many receipts the collapsed view leads with.
   *
   * `highlightReceipts` in `lib/trust-forward/receipts.ts` refuses to default
   * this on purpose — "there is no authored default highlight count anywhere in
   * the handoff", and a default buried in a library would quietly become the
   * product's answer to a question that belongs to the surface or to Ben. The
   * surface is entitled to choose, and this one chooses three: enough to show a
   * pattern, few enough that "See full" is a real second step rather than a
   * formality. It stays a prop so the choice can move without touching this
   * file.
   */
  highlightCount?: number;
  /** Where both continue controls point. `→ /tf` in UX_COPY.md and the plan. */
  fullHref?: string;
  /** The eight axis-end captions, once `content/` carries them. See ShipBars. */
  axisEndLabels?: Readonly<Record<ShipAxis, ShipAxisEnds>>;
  /**
   * INSTALLATION.md: if the page load detects a newer stamp, the final result
   * also offers `Start latest version`. That detection, its copy and its ledger
   * events belong to the version owner, so this is a slot rather than a feature
   * — the reveal reserves the place the ruling puts it ("No upgrade controls
   * earlier in the flow") without inventing the control.
   */
  versionNotice?: ReactNode;
}

/**
 * THE GAP, named, so it is greppable next to the four already recorded on
 * `TRUST_FORWARD_UNSOURCED_SURFACES`. The seven `RevealActionLabels` strings
 * have no home in `content/trust-forward/` yet. The fix is a labels record
 * there — tagged `implementation_authored_under_ben_approved_rule`, since
 * `INSTALLATION.md` supplies the RULE for each control and no wording — passed
 * in as `labels`. Do not satisfy this by typing the labels into `app/` or
 * `components/`.
 */
export const TODO_REVEAL_ACTION_LABELS = null;

/**
 * The reflections that have words in them.
 *
 * A skipped reflection is not an empty quotation. The learner declined, and
 * `REFLECTION.actions.skip` / `alwaysSkip` make declining a first-class choice
 * the ledger records as a preference; an empty quote mark under a case label
 * would report a decision as a failure to write. Emptiness is judged on a
 * trimmed COPY and the original string is what renders, so a reflection that is
 * deliberately whitespace-shaped keeps its shape while one that is only
 * whitespace does not become a blank card.
 *
 * The order is the caller's. Not sorted, not reversed, not grouped: "No
 * synthesis" covers arrangement as much as it covers wording.
 */
export function writtenReflections(
  reflections: readonly RevealReflection[]
): readonly RevealReflection[] {
  return reflections.filter((reflection) => reflection.text.trim().length > 0);
}

export function Reveal({
  result,
  reflections,
  handle = null,
  clipboardFields = null,
  labels = null,
  onExportMarkdown,
  onExportJson,
  onCopySummary,
  onReopenDecisions,
  onStartOver,
  onContinueToFull,
  onExportFirst,
  onViewed,
  onReceiptsOpened,
  onSeeAllReceipts,
  highlightCount = 3,
  fullHref = "/tf",
  axisEndLabels,
  versionNotice
}: RevealProps) {
  const [receiptsOpen, setReceiptsOpen] = useState(false);
  const [seeAll, setSeeAll] = useState(false);
  const [copyOpen, setCopyOpen] = useState(false);
  const [confirmingReset, setConfirmingReset] = useState(false);
  const [copySelection, setCopySelection] = useState<readonly ClipboardSummaryFieldId[]>(() =>
    (clipboardFields ?? []).filter((field) => field.defaultChecked).map((field) => field.id)
  );

  const viewedFired = useRef(false);
  useEffect(() => {
    if (viewedFired.current) return;
    viewedFired.current = true;
    if (onViewed) onViewed();
  }, [onViewed]);

  /**
   * The profile body, cross-checked. `profileFor` throws when the result's code
   * and the sixteen-profile body disagree — the one bug that would otherwise
   * render as a perfectly plausible page.
   */
  const profile = profileFor(result.ship);

  /** The sanctioned form, validated by its own constructor. */
  const patternLabel = observedPatternLabel(result.ship.code);

  /**
   * A SORTED COPY. `result.receipts` is the trail in case-then-decision order
   * and stays that way; the highlight view applies the ruling's three-term order
   * — SHIP contribution, later case, stable authored order — to a copy of it.
   */
  const highlights = useMemo(
    () => result.receipts.slice().sort(compareReceiptsForHighlight).slice(0, highlightCount),
    [result.receipts, highlightCount]
  );
  const shownReceipts = seeAll ? result.receipts : highlights;

  const written = writtenReflections(reflections);

  function toggleReceipts() {
    const next = !receiptsOpen;
    setReceiptsOpen(next);
    if (next && onReceiptsOpened) onReceiptsOpened();
  }

  function showAllReceipts() {
    setSeeAll(true);
    if (onSeeAllReceipts) onSeeAllReceipts();
  }

  function toggleCopyField(id: ClipboardSummaryFieldId) {
    setCopySelection((current) =>
      current.includes(id) ? current.filter((entry) => entry !== id) : [...current, id]
    );
  }

  function exportBeforeReset() {
    if (onExportFirst) onExportFirst();
    else onExportJson();
  }

  return (
    <div className={styles.reveal}>
      {/* 1. The completion statement. */}
      <section className={styles.block}>
        <h2 className={styles.blockHeading}>
          {finalRevealBlock.headline}
          <span className={styles.blockSubheading}>{finalRevealBlock.subheadline}</span>
        </h2>
        {finalRevealBlock.body.map((sentence) => (
          <p className={styles.paragraph} key={sentence}>
            {sentence}
          </p>
        ))}
      </section>

      <hr className={styles.rule} />

      {/* 2. The result. */}
      <section aria-label={patternLabel} className={styles.block}>
        <div className={styles.result}>
          {handle ? <p className={styles.handle}>{handle}</p> : null}
          <p className={styles.patternLabel}>{RESULT.label}</p>
          <p className={styles.code}>{result.ship.code}</p>
          <p className={styles.profileName}>{profile.name}</p>
          <p className={styles.specialAbility}>{profile.specialAbility}</p>
          <ShipBars endLabels={axisEndLabels} ship={result.ship} />
          <p className={styles.shipExplanation}>{RESULT.shipExplanation}</p>
        </div>

        <p className={styles.synthesis}>{profile.synthesis}</p>
        <p className={styles.narrative}>{result.narrative}</p>
        <p className={styles.closingLine}>{deterministicSummaryFraming.closingLine}</p>
        <p className={styles.disclaimer}>{RESULT.disclaimer}</p>

        <div className={styles.receipts}>
          <button
            aria-expanded={receiptsOpen}
            className={styles.disclosureButton}
            onClick={toggleReceipts}
            type="button"
          >
            {RESULT.receiptsToggle}
          </button>
          {receiptsOpen ? (
            <>
              <ul className={styles.receiptList}>
                {shownReceipts.map((receipt) => (
                  <li className={styles.receipt} key={receipt.decisionId}>
                    {receipt.phrase}
                  </li>
                ))}
              </ul>
              {seeAll ? null : (
                <button
                  className={styles.disclosureButton}
                  onClick={showAllReceipts}
                  type="button"
                >
                  {RESULT.receiptsSeeAll}
                </button>
              )}
            </>
          ) : null}
        </div>
      </section>

      <hr className={styles.rule} />

      {/* 3. What you actually wrote. Verbatim, in order, with no synthesis. */}
      {written.length > 0 ? (
        <section className={styles.block}>
          <h2 className={styles.blockHeading}>{learnerWordsBlock.heading}</h2>
          <p className={styles.wordsNote}>{learnerWordsBlock.note}</p>
          <ul className={styles.wordsList}>
            {written.map((reflection) => (
              <li className={styles.wordsItem} key={reflection.caseNumber}>
                <span className={styles.wordsLabel}>
                  {learnerWordsCaseLabel(reflection.caseNumber)}
                </span>
                <p className={styles.wordsText}>{reflection.text}</p>
              </li>
            ))}
          </ul>
        </section>
      ) : null}

      {/*
        THE PROFESSIONAL-SUMMARY INSERTION POINT. Nothing renders here, on
        purpose. content/trust-forward/copy.ts exports
        TODO_RESULT_PROFESSIONAL_SUMMARY as null because the recovered
        market_copy column and layer 07 give contradictory instructions about
        what this block is, and layer 07 marks the surviving summary
        implementation-authored from market vocabulary rather than recovered.
        Until that copy exists and is approved through the repository's normal
        mechanics, an empty space is the honest rendering: a placeholder
        sentence here would carry the provenance of the recovered blocks either
        side of it, and nothing on the page would record the difference.
      */}

      {/* Export and copy. Unlocked because a result exists at all. */}
      {labels ? (
        <section className={styles.block}>
          <div className={styles.actions}>
            <button className={styles.button} onClick={onExportMarkdown} type="button">
              {labels.exportMarkdown}
            </button>
            <button className={styles.button} onClick={onExportJson} type="button">
              {labels.exportJson}
            </button>
            {clipboardFields && clipboardFields.length > 0 ? (
              <button
                aria-expanded={copyOpen}
                className={styles.button}
                onClick={() => setCopyOpen(!copyOpen)}
                type="button"
              >
                {labels.copySummary}
              </button>
            ) : null}
          </div>

          {/*
            EXPORT_SPEC.md: "Clipboard summary is local-only and uses checkbox
            field selection before copy." The list is an opt-OUT — everything the
            spec lists is checked when it opens — and it shows each VALUE, not
            only its label, so a learner sees what they are about to paste
            somewhere before they paste it. Receipts, reflections and the ledger
            are deliberately not offered here; those live in the two downloads.
          */}
          {copyOpen && clipboardFields ? (
            <div className={styles.copyPanel}>
              <ul className={styles.fieldList}>
                {clipboardFields.map((field) => (
                  <li key={field.id}>
                    <label className={styles.field}>
                      <input
                        checked={copySelection.includes(field.id)}
                        onChange={() => toggleCopyField(field.id)}
                        type="checkbox"
                      />
                      <span className={styles.fieldBody}>
                        <span className={styles.fieldLabel}>{field.label}</span>
                        <span className={styles.fieldValue}>{field.value}</span>
                      </span>
                    </label>
                  </li>
                ))}
              </ul>
              <div className={styles.actions}>
                <button
                  className={cx(styles.button, styles.buttonPrimary)}
                  onClick={() => onCopySummary(copySelection)}
                  type="button"
                >
                  {labels.copyConfirm}
                </button>
              </div>
            </div>
          ) : null}
        </section>
      ) : null}

      <hr className={styles.rule} />

      {/* 4. The closing upsell. */}
      <section className={cx(styles.block, styles.upsell)}>
        <h2 className={styles.blockHeading}>{closingUpsell.heading}</h2>
        <p className={styles.upsellLead}>{closingUpsell.descriptor}</p>
        <p className={styles.paragraph}>{closingUpsell.couldLine}</p>
        <p className={styles.paragraph}>{closingUpsell.couldNotHeading}</p>
        <ul className={styles.couldNotList}>
          {closingUpsell.couldNotItems.map((item) => (
            <li className={styles.couldNotItem} key={item}>
              {item}
            </li>
          ))}
        </ul>
        <p className={styles.paragraph}>{closingUpsell.fullBridgeLead}</p>
        {/*
          The bridge and its confidentiality sentence are ONE group. copy.ts:
          "real cases drawn from Ben Chan's actual professional experience" is a
          claim about real clients and colleagues, and the sentence saying how
          they are protected is what makes the first safe to publish. A renderer
          that shows the bridge without it has published the claim without its
          limit, so no layout change may separate these two.
        */}
        <div className={styles.bridgeGroup}>
          <p className={styles.bridge}>{closingUpsell.fullBridge}</p>
          <p className={styles.confidentiality}>{closingUpsell.fullBridgeConfidentiality}</p>
        </div>
        <p className={styles.evidenceLine}>{closingUpsell.evidenceLine}</p>
        <h3 className={styles.promiseHeading}>{closingUpsell.corePromiseHeading}</h3>
        <p className={styles.paragraph}>{closingUpsell.corePromiseBody}</p>
        <div className={styles.actions}>
          <a
            className={cx(styles.button, styles.buttonPrimary)}
            href={fullHref}
            onClick={onContinueToFull}
          >
            {closingUpsell.ctaLabel}
          </a>
        </div>
      </section>

      {/*
        The local controls. Two authored strings point at the same destination —
        UX_COPY.md's completion CTA for this screen, and the recovered upsell's
        own close above — and both render, because dropping either is an
        authority ruling between layer 01 and layer 06 that a component is not
        entitled to make. They are given different weight instead: the upsell
        closes its own argument, and this row is the utility rail.
      */}
      <section className={styles.block}>
        <div className={styles.actions}>
          <a className={styles.button} href={fullHref} onClick={onContinueToFull}>
            {RESULT.completionCta}
          </a>
          <button className={styles.button} onClick={onReopenDecisions} type="button">
            {RESULT.secondaryCta}
          </button>
          {labels && !confirmingReset ? (
            <button
              className={cx(styles.button, styles.buttonQuiet)}
              onClick={() => setConfirmingReset(true)}
              type="button"
            >
              {RESULT.destructiveCta}
            </button>
          ) : null}
        </div>

        {/*
          Step two of the destructive confirmation. "Export first" leads,
          because this learner has a complete run and clearing local storage is
          the only way to lose it — INSTALLATION.md puts the offer here rather
          than inside a warning sentence. Cancel is present and unweighted, and
          the confirm carries no alarm colour: this is the learner's own local
          data and they asked for the control.
        */}
        {labels && confirmingReset ? (
          <div className={styles.confirmRow}>
            <button className={styles.button} onClick={exportBeforeReset} type="button">
              {labels.startOverExportFirst}
            </button>
            <button className={styles.button} onClick={onStartOver} type="button">
              {labels.startOverConfirm}
            </button>
            <button
              className={cx(styles.button, styles.buttonQuiet)}
              onClick={() => setConfirmingReset(false)}
              type="button"
            >
              {labels.startOverCancel}
            </button>
          </div>
        ) : null}

        {versionNotice ? <div className={styles.versionNotice}>{versionNotice}</div> : null}
      </section>
    </div>
  );
}
